---
## Yaourt

- name: add archlinuxfr repository to pacman
  lineinfile:
    dest: /etc/pacman.conf
    state: present
    line: "{{ item }}"
  with_items:
    - "[archlinuxfr]"
    - "SigLevel = Never"
    - "Server = http://repo.archlinux.fr/$arch"

- name: install yaourt
  pacman:
    name: yaourt
    state: latest
    update_cache: yes

#- name: import tor-browser gpg key
#  command: gpg --keyserver keys.gnupg.net --recv-keys 2E1AC68ED40814E0
#- name: GPG key for vim-youcompleteme-git
#  shell: "sudo gpg --recv-key 1EB2638FF56C0C53"

- name: install yaourt packages (this can take some time...)
  yaourt:
    name: "{{item}}"
    state: latest
  ignore_errors: yes
  with_items:
    - oh-my-zsh-git
    - xfce4-volumed
    - caffeine-ng
    - i3lock-wrapper
    - pycharm-community
    - python2-cli53
    - screencloud
    - skype4pidgin-git
    - roccatkonextdconfig
    - spotify
    - teamviewer
    - whatpulse
    - zabbix-agent
    - numix-circle-icon-theme-git
    - numix-icon-theme-git
    - google-talkplugin
    - vim-youcompleteme-git
    - chromium-pepper-flash
    - ttf-font-awesome
    - mpdscribble
    - tor-browser-en
    - apache-tools
    - steam-libs
    - imwheel
