---

- name: create user
  user:
    name: "{{system_username}}"
    password: "{{user_password|password_hash('sha512') }}"
    state: present
    groups: "docker,wheel,users,lp,storage,audio,input"
    append: yes
    shell: /bin/zsh
    update_password: always


- name: create default directories
  file:
    dest: "/home/{{system_username}}/{{item}}"
    state: directory
    owner: "{{system_username}}"
    group: "{{system_group}}"
  with_items:
    - Downloads
    - Photos
    - Music
    - ownCloud
