---

- name: copy etc files
  copy:
    src: "./files/etc/{{ item.path }}"
    dest: "/etc/{{ item.dest }}"
    owner: "{{root_user}}"
    group: "{{root_group}}"
    mode: "0644"
  with_items:
     - { path: 'fancontrol-desktop.j2', dest: 'fancontrol' }
     - { path: 'mpd-desktop.conf.j2', dest: 'mpd.conf' }
     - { path: 'modules-load.d/load_these.conf.j2', dest: 'modules-load.d/load_these.conf' }
     - { path: 'sysctl.d/99-sysctl.conf.j2', dest: 'sysctl.d/99-sysctl.conf' }
     - { path: 'pulse/default.pa.j2', dest: 'pulse/default.pa' }
  sudo: yes
  when: configure_catalyst.0 is defined # Since I only run fancontrol on desktop, which runs catalyst...

- name: disable lm_sensors service
  service:
    name: lm_sensors
    state: started
  sudo: yes
  when: configure_catalyst.0 is defined

- name: enable default services
  service:
    name: "{{item}}"
    state: started
  sudo: yes
  with_items:
    - ntpd
    - dhcpcd
    - cups-browsed
    - avahi-daemon
    - lightdm
    - fancontrol
    - docker
    - sshd
    - mpd

- file: path=/media/nfs/shares state=directory mode=0755

- name: fstab | Ensure fstab uses nobootwait and noatime
  mount:
    name: "/media/nfs/shares"
    src: "sc0rian.mooo.com:/home/shares"
    fstype: "nfs4"
    opts: "users,auto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14,noatime,nolock"
    state: "mounted"
  sudo: yes