# Download an up-to-date pacman mirror list for Europe
# add multilib and infinality (fonts) repositories
# install catalyst drivers, when configure_catalyst is defined
# install base packages
---

- name: Ensure that ~/.gnupg directory exists
  file:
    path: '{{ root_user + "/.gnupg" }}'
    state: 'directory'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: '0700'
  sudo: yes

- name: download pacman mirror list
  get_url:
    url: "https://www.archlinux.org/mirrorlist/?country=FR&country=DE&country=IE&country=LU&country=CH&country=GB&protocol=http&ip_version=4&ip_version=6&use_mirror_status=on"
    dest: "/etc/pacman.d/mirrorlist"

- name: "uncomment `#Server` in pacman mirror list"
  replace:
    dest: "/etc/pacman.d/mirrorlist"
    regexp: '^#Server'
    replace: 'Server'

# Enable multilib

- name: add multilib
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "[multilib]"
    regexp: "^\\[multilib\\]"
    insertafter: "^#\\[multilib\\]"

- name: add multilib (cont)
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "Include = /etc/pacman.d/mirrorlist"
    insertafter: "^\\[multilib\\]"
    regexp: "Include = /etc/pacman.d/mirrorlist"

## infinality font bundle

- name: add infinality-bundle key
  shell: "pacman-key -r 962DDE58 && pacman-key --lsign-key 962DDE58"
  changed_when: false
  sudo: yes

- name: add infinality-bundle # https://wiki.archlinux.org/index.php/Unofficial_user_repositories#infinality-bundle
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "[infinality-bundle]"
  sudo: yes

- name: add infinality-bundle (cont)
  lineinfile:
    dest: /etc/pacman.conf
    state: present
    line: "Server = http://bohoomil.com/repo/$arch"
    insertafter: "^\\[infinality\\-bundle\\]"
  sudo: yes

- name: add infinality-bundle-fonts # https://wiki.archlinux.org/index.php/Unofficial_user_repositories#infinality-bundle
  lineinfile:
    dest: /etc/pacman.conf
    state: present
    line: "[infinality-bundle-fonts]"
  sudo: yes

- name: add infinality-bundle-fonts (cont)
  lineinfile:
    dest: /etc/pacman.conf
    state: present
    line: "Server = http://bohoomil.com/repo/fonts"
    insertafter: "^\\[infinality\\-bundle\\-fonts\\]"
  sudo: yes

## Catalyst
- name: add catalyst key Vi0l0
  shell: "pacman-key -r 653C3094 && pacman-key --lsign-key 653C3094"
  changed_when: false
  when: configure_catalyst.0 is defined
  sudo: yes

# https://wiki.archlinux.org/index.php/Unofficial_user_repositories#catalyst
# https://wiki.archlinux.org/index.php/AMD_Catalyst#Xorg_repositories
- name: add catalyst and xorg
  sudo: yes
  when: configure_catalyst.0 is defined
  blockinfile:
    dest: /etc/pacman.conf
    insertbefore: "^\\[core\\]"
    block: |
      [catalyst]
      Server = http://catalyst.wirephire.com/repo/catalyst/$arch
      ## Mirrors, if the primary server does not work or is too slow:
      #Server = http://70.239.162.206/catalyst-mirror/repo/catalyst/$arch
      #Server = http://mirror.rts-informatique.fr/archlinux-catalyst/repo/catalyst/$arch
      #Server = http://mirror.hactar.bz/Vi0L0/catalyst/$arch
      [xorg117]
      Server = http://catalyst.wirephire.com/repo/xorg117/$arch
      ## Mirrors, if the primary server does not work or is too slow:
      Server = http://mirror.rts-informatique.fr/archlinux-catalyst/repo/xorg117/$arch
      Server = http://mirror.hactar.bz/Vi0L0/xorg117/$arch

- name: install pacman packages
  pacman:
    name: "{{item}}"
    state: latest
    update_cache: yes
  sudo: yes
  when: setup_packages.0 is defined
  with_items:
# system packages
    - curl
    - htop
    - iotop
    - powertop
    - glances
    - sudo
    - zsh
    - downgrade
    - udiskie
    - avahi
    - xbindkeys
    - tlp
    - acpi
    - acpid
    - alsa-utils
    - pulseaudio
    - keychain
    - rsync
    - ntp
    - smartmontools
    - strace
    - dhcpcd
    - dhclient
    - diffutils
    - lm_sensors
    - jdk8-openjdk
    - fuse-exfat
    - nfs-utils
    - logrotate
    - openssh

# display packages
    - xorg-xbacklight
    - xorg-xsetroot
    - xorg-server
    - xorg-server-devel
    - arandr
    - xorg-xinit
    - lightdm
    - lightdm-gtk-greeter
    - redshift

# window manager packages
    - i3-wm
    - dmenu
#    - i3lock
    - i3status
    - xfce4-notifyd
    - conky
    - screenfetch
    - gtk-theme-orion
    - numix-themes
    - lxappearance

# compression packages
    - xarchiver-gtk2
    - zip
    - unzip
    - unrar
    - bzip2
    - gzip
    - tar
    - p7zip

# virtualization packages
    - docker

# file packages
    - thunar
    - thunar-media-tags-plugin
    - thunar-archive-plugin
    - ranger
    - libgphoto2 #gphoto2
    - gvfs gvfs-gphoto2 gvfs-mtp gvfs-smb # have to be bundled together as they depend on each other

# office packages
    - libreoffice-fresh
    - gthumb
    - owncloud-client
    - chromium
    - transmission-qt
    - keepass
    - sublime-text-dev # archlinuxfr
    - variety
    - gnome-keyring
    - vim-jedi
    - vim

# printing packages
    - cups

# chat packages
    - pidgin
    - skype
#    - weechat

# font packages
    - freetype2-infinality-ultimate
    - fontconfig-infinality-ultimate
    - cairo-infinality-ultimate
    - ttf-dejavu
    - noto-fonts
    - noto-fonts-cjk

# gaming/video/music packages
    - steam
    - vlc
    - kodi
    - ncmpcpp
    - mpd
    - mpc
    - pavucontrol
    - gstreamer0.10-base-plugins
#    - gstreamer0.10-good-plugins
#    - gstreamer0.10-bad-plugins
#    - gstreamer0.10-ugly-plugins

# terminal/work packages
    - gist
    - ncdu
    - xsel
    - ranger
    - dos2unix
    - grml-zsh-config
    - terminator
    - git
    - git-review

# Python2 packages
    - python2
    - ipython2
    - python2-virtualenv
    - python2-pip
    - python2-jedi
 # Python3
    - python
    - python-virtualenv
    - ipython
    - python-pip

