---

- name: create user
  user:
    name: "{{system_username}}"
    password: "{{user_password|password_hash('sha512') }}"
    state: present
    groups: "printadmin,docker,wheel,users,lp"
    append: yes
    shell: /bin/zsh
    update_password: always
  sudo: yes


- name: create default directories
  file:
    dest: "/home/{{system_username}}/{{item}}"
    state: directory
    owner: "{{system_username}}"
    group: "{{system_group}}"
  with_items:
    - Downloads
    - Photos
    - Music

- name: copy Templates folder
  copy:
    src: "files/home/Templates"
    dest: "/home/{{system_username}}/Templates"
    owner: "{{system_username}}"
    group: "{{system_group}}"
    mode: 0644

- name: setup dotfile symlinks /home/username/.dotfile
  file:
    src: "/home/{{system_username}}/ownCloud/dotfiles/{{ item.path }}"
    dest: "/home/{{system_username}}/{{ item.path }}"
    state: link
  with_items:
    - { path: '.zshrc' }
    - { path: '.vimrc' }
    - { path: '.screenlayout' }
    - { path: '.i3' }
    - { path: '.weechat' }
    - { path: '.purple' }
    - { path: '.ssh'}
    - { path: '.boto' }

- name: setup path symlinks /home/username/
  file:
    src: "/home/{{system_username}}/ownCloud/{{ item.path }}"
    dest: "/home/{{system_username}}/{{ item.dest }}"
    state: link
  with_items:
    - { path: 'Documents', dest: 'Documents' }
    - { path: 'linaro/linaro-its-tools', dest: 'linaro-its-tools' }
    - { path: 'Scripts', dest: 'Scripts' }
    - { path: 'GitHub', dest: 'GitHub' }

- name: setup path symlinks /home/username/.config
  file:
    src: "/home/{{system_username}}/ownCloud/config/{{ item.path }}"
    dest: "/home/{{system_username}}/.config/{{ item.path }}"
    state: link
  with_items:
    - { path: 'sublime-text-2' }
    - { path: 'sublime-text-3' }
    - { path: 'terminator'}
    - { path: 'KeePass' }
    - { path: 'transmission' }
    - { path: 'Clementine' }
    - { path: 'caffeine' }
    - { path: 'spotify' }