---
- name: copy xorg.conf.d for laptop
  copy:
    src: "files/etc/xorg.conf.d/laptop/mac/{{item}}"
    dest: "/etc/X11/xorg.conf.d/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20-intel.conf
    - 50-synaptics.conf
  when: configure_intel_mac.0 is defined

- name: copy xorg.conf.d for laptop (dell)
  copy:
    src: "files/etc/xorg.conf.d/laptop/dell/{{item}}"
    dest: "/etc/X11/xorg.conf.d/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20-intel.conf
    - 50-synaptics.conf
  when: configure_intel_dell.0 is defined


- name: install xf86-video-amdgpu
  pacman:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - xf86-video-amdgpu
  when: configure_video_amdgpu.0 is defined
