---
- name: install aur packages
  command: "pacaur -S --noconfirm --noedit {{item}}"
  become: no
  #  ignore_errors: yes
  with_items:
    - apache-tools
    - caffeine-ng
    - chromium-pepper-flash
    - dragondisk
    - flacon #flac
    - google-chrome
    - google-talkplugin
    - i3lock-wrapper
    - imwheel
    - lib32-librtmp0 #tombraider etc
    - mpdscribble
    - numix-circle-icon-theme-git
    - numix-icon-theme-git
    - oh-my-zsh-git
    - pasystray
    - powerline-fonts-git #zsh theme agnoster
    - purple-facebook
    - purple-skypeweb-git
    - pycharm-community
    - polybar
    - reflector-timer
    - roccat-tools-full
    - samsung-printers
    - screencloud
    - skypeforlinux-bin
    - spotify
    - spotify-adkiller-git
    - sublime-text-dev
    - teamviewer
    - tor-browser-en
    - ttf-font-awesome
    - ttf-inconsolata-g #terminator
    - vim-youcompleteme-git
    - whatpulse
    - gifcast
