---
- name: install aur packages
#  command: "pacaur -Qs {{item}}"
  command: "trizen -S --noconfirm --noedit {{item}}"
  become: no
  ignore_errors: yes
  with_items:
    - caffeine-ng
    - flacon #flac
    - google-chrome
    - google-talkplugin
    - gsimplecal
    - imwheel
    - mpdscribble
    - numix-circle-icon-theme-git
    - numix-icon-theme-git
    - oh-my-zsh-git
    - pasystray
    - powerline-fonts-git #zsh theme agnoster
    - purple-facebook
    - polybar
    - purple-skypeweb-git
    - reflector-timer
#    - roccat-tools-full
    - samsung-printers
    - screencloud
    - imgur-screenshot-git
    - skypeforlinux-preview-bin
    - spotify
    - blockify
    - sublime-text-dev
    - ttf-font-awesome-4
    - ttf-inconsolata-g #terminator
#    - vim-youcompleteme-git
#    - gifcast
#    - dell-srvadmin
