---
- name: copy etc files
  copy:
    src: "./files/etc/{{ item.path }}"
    dest: "/etc/{{ item.dest }}"
    owner: "{{root_user}}"
    group: "{{root_group}}"
    mode: "0644"
    backup: yes
  with_items:
     - { path: 'sysctl.d/99-sysctl.conf.j2', dest: 'sysctl.d/99-sysctl.conf' }
     - { path: 'makepkg.conf', dest: 'makepkg.conf' }
     - { path: 'fuse.conf', dest: 'fuse.conf' }

- name: enable default services
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  with_items:
   # - ntpdate.service
    - dhcpcd
    - cups-browsed
    - org.cups.cupsd.service
    - avahi-daemon
    - gdm
    - docker
    - sshd

- name: enable user based services
  become: no
  systemd:
    state: started
    enabled: yes
    name: "{{item}}"
    user: yes
  with_items:
    - mpd
    - mpdscribble
    - rclone

- name: Ensure gdrive directory exists
  file:
    path: "{{gdrive_share}}"
    state: "directory"
    mode: "0755"
    owner: "{{system_username}}"
    group: "{{system_group}}"

- name: Ensure nfs directory exists
  file:
    path: "{{nfs_share}}"
    state: "directory"
    mode: "0755"
  ignore_errors: True
  when: nfs_mount.0 is defined

- name: Ensure fstab uses nobootwait and noatime
  mount:
    name: "{{nfs_share}}"
    src: "sc0rian.mooo.com:/"
    fstype: "nfs4"
    opts: "noauto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14,x-systemd.idle-timeout=1min"
    state: "mounted"
  ignore_errors: "yes"
  when: nfs_mount.0 is defined

# whatpulse / not used
#- name: allow conky to access wireless values
#  command: "setcap cap_net_raw,cap_net_admin=eip /usr/bin/conky"
