---
- name: copy etc files
  copy:
    src: "./files/etc/{{ item.path }}"
    dest: "/etc/{{ item.dest }}"
    owner: "{{root_user}}"
    group: "{{root_group}}"
    mode: "0644"
    backup: yes
  with_items:
     - { path: 'fancontrol-desktop.j2', dest: 'fancontrol' }
     - { path: 'asound.conf.j2', dest: 'asound.conf' }
     - { path: 'modules-load.d/load_these.conf.j2', dest: 'modules-load.d/load_these.conf' }
     - { path: 'sysctl.d/99-sysctl.conf.j2', dest: 'sysctl.d/99-sysctl.conf' }
  when: configure_catalyst.0 is defined 

# Since I only run fancontrol on desktop, which runs catalyst...
- name: disable lm_sensors service
  service:
    name: lm_sensors
    state: stopped
  when: configure_catalyst.0 is defined

# Disable due to stupid sensors moving around on bootup
- name: enable default services
  service:
    name: "{{item}}"
    state: started
  with_items:
    - ntpd
    - dhcpcd
    - cups-browsed
    - avahi-daemon
    - lightdm
    - fancontrol
    - docker
    - sshd
    - reflector.timer

# NFS Share
- name: Ensure fstab directory exists
  file: 
    path: "{{nfs_share}}"
    state: "directory"
    mode: "0755"
  ignore_errors: True

- name: Ensure fstab uses nobootwait and noatime
  mount:
    name: "{{nfs_share}}"
    src: "sc0rian.mooo.com:/"
    fstype: "nfs4"
    opts: "noauto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14,x-systemd.idle-timeout=1min"
    state: "mounted"

- name: allow conky to access wireless values
  command: "setcap cap_net_raw,cap_net_admin=eip /usr/bin/conky"
