---
## Yaourt

- name: add archlinuxfr repository to pacman
  lineinfile:
    dest: /etc/pacman.conf
    state: present
    line: "{{ item }}"
  with_items:
    - "[archlinuxfr]"
    - "SigLevel = Never"
    - "Server = http://repo.archlinux.fr/$arch"
  sudo: yes

- name: install yaourt
  pacman:
    name: yaourt
    state: latest
    update_cache: yes
  sudo: yes

- name: import tor-browser gpg key
  command: gpg --keyserver keys.gnupg.net --recv-keys 2E1AC68ED40814E0

- name: install yaourt packages (this can take some time...)
  yaourt:
    name: "{{item}}"
    state: latest
  ignore_errors: yes
  with_items:
    - oh-my-zsh-git
    - apachedirectorystudio
    - xfce4-volumed
    - caffeine-ng
 #   - conkyclementine-bzr
    - i3lock-wrapper
    - keepass-plugin-http
    - pycharm-community
    - python2-cli53
    - screencloud
    - skype4pidgin-git
    - solaar
    - spotify
    - teamviewer
    - whatpulse
    - zabbix-agent
    - numix-circle-icon-theme-git
    - numix-icon-theme-git
    - google-talkplugin
 #   - vim-youcompleteme-git
    - chromium-pepper-flash
    # - backintime-cli
    # - backintime
    - ttf-font-awesome
    - mpdscribble
    - tor-browser-en
