---
- name: create user
  user:
    name: "{{system_username}}"
    password: "{{user_password}}"
    state: present
    groups: printadmin,docker,wheel,users,lp
    append: yes
    shell: /bin/zsh
  register: result
  sudo: yes
  when: user_password.0 is defined

- name: create default directories
  file:
    dest: "/home/{{system_username}}/{{item}}"
    state: directory
    owner: "{{system_username}}"
    group: "{{system_group}}"
  with_items:
    - Downloads
    - Photos
    - Music
    - Templates