---
- name: install aur packages
  command: "pacaur -S --noconfirm --noedit {{item}}"
  become: no
  #  ignore_errors: yes
  with_items:
    - oh-my-zsh-git
    - caffeine-ng
    - i3lock-wrapper
    - pycharm-community
    - screencloud
    - roccat-tools-full
    - spotify
    - spotify-adkiller
    - teamviewer
    - whatpulse
    - numix-circle-icon-theme-git
    - numix-icon-theme-git
    - google-talkplugin
    - vim-youcompleteme-git
    - chromium-pepper-flash
    - ttf-font-awesome
    - mpdscribble
    - tor-browser-en
    - apache-tools
    - imwheel
    - sublime-text-dev
    - pasystray
    - ttf-inconsolata-g #terminator
#    - steam-native
    - powerline-fonts-git #zsh theme agnoster
    - google-chrome
    - reflector-timer
    - purple-skypeweb-git
    - skypeforlinux-bin
    - lib32-librtmp0 #tombraider etc
    - samsung-ml1640
    - flacon #flac
    - dragondisk
