---
- name: copy etc files
  copy:
    src: "./files/etc/{{ item.path }}"
    dest: "/etc/{{ item.dest }}"
    owner: "{{root_user}}"
    group: "{{root_group}}"
    mode: "0644"
    backup: yes
  with_items:
     - { path: 'sysctl.d/99-sysctl.conf.j2', dest: 'sysctl.d/99-sysctl.conf' }
     - { path: 'systemd/system/reflector.service', dest: 'systemd/system/reflector.service' }
     - { path: 'systemd/system/reflector.timer', dest: 'systemd/system/reflector.timer' }

- name: enable default services
  service:
    name: "{{item}}"
    state: started
  with_items:
    - ntpd
    - dhcpcd
    - cups-browsed
    - avahi-daemon
    - lightdm
    - docker
    - sshd
    - reflector.service
    - reflector.timer

# NFS Share
- name: Ensure fstab directory exists
  file: 
    path: "{{nfs_share}}"
    state: "directory"
    mode: "0755"
  ignore_errors: True

- name: Ensure fstab uses nobootwait and noatime
  mount:
    name: "{{nfs_share}}"
    src: "sc0rian.mooo.com:/"
    fstype: "nfs4"
    opts: "noauto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14,x-systemd.idle-timeout=1min"
    state: "mounted"

- name: allow conky to access wireless values
  command: "setcap cap_net_raw,cap_net_admin=eip /usr/bin/conky"
