---
- name: add archlinuxfr repository to pacman
  lineinfile:
    dest: /etc/pacman.conf
    state: present
    line: "{{ item }}"
  with_items:
    - "[archlinuxfr]"
    - "SigLevel = Never"
    - "Server = http://repo.archlinux.fr/$arch"

- name: install yaourt
  pacman:
    name: yaourt
    state: latest

# - name: install yaourt packages
#   pacman:
#     name: "{{item}}"
#     state: latest
#     aur: yes
#   sudo: yes
#   register: rawr
#   ignore_errors: yes
#   with_items:
#     - oh-my-zsh-git
#     - clementine-git
# - debug: var=rawr
