---

- name: copy xorg.conf.d for laptop
  copy:
    src: "files/etc/xorg.conf.d/laptop/{{item}}"
    dest: "/etc/X11/xorg.conf.d/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20-intel.conf
    - 50-synaptics.conf

- name: set dpi settings
  replace:
    dest: "/etc/lightdm/lightdm.conf"
    regexp: '^#xserver-command='
    replace: 'xserver-command=X -dpi 120'
