---

- name: copy xorg.conf.d for laptop
  copy:
    src: "files/etc/xorg.conf.d/laptop/{{item}}"
    dest: "/etc/X11/xorg.conf.d/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20-intel.conf
    - 30-whatpulse-touchpad-rules.conf
    - 50-synaptics.conf

- name: set dpi settings
  replace:
    dest: "/etc/lightdm/lightdm-gtk-greeter.conf"
    regexp: '^#xft-dpi='
    replace: 'xft-dpi=140'

- name: set dpi
  replace:
    dest: "/etc/X11/xinit/xinitrc.d/xft-settings.sh"
    regexp: "^Xft.dpi:"
    replace: "Xft.dpi:        140"
