---

- name: setup dotfile symlinks /home/username/.dotfile
  file:
    src: "/home/{{system_username}}/ownCloud/dotfiles/{{ item.path }}"
    dest: "/home/{{system_username}}/{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - { path: '.zshrc', dest: '.zshrc' }
    - { path: '.vimrc', dest: '.vimrc' }
    - { path: '.screenlayout', dest: '.screenlayout' }
    - { path: '.ssh', dest: '.ssh'}
    - { path: '.mpdscribble', dest: '.mpdscribble' }
    - { path: '.gist', dest: '.gist' }
    - { path: '.gitconfig', dest: '.gitconfig' }
    - { path: '.gnupg', dest: '.gnupg' }
    - { path: '.rclone.conf', dest: '.rclone.conf' }
    - { path: '.aws', dest: '.aws' }
    - { path: '.atom', dest: '.atom' }
    - { path: '.password-store', dest: '.password-store' }

  when: setup_owncloud.0 is defined

- name: setup path symlinks /home/username/
  file:
    src: "/home/{{system_username}}/ownCloud/{{ item.path }}"
    dest: "/home/{{system_username}}/{{ item.dest }}"
    state: link
  with_items:
    - { path: 'Documents', dest: 'Documents' }
    - { path: 'Linaro', dest: 'Linaro' }
    - { path: 'Scripts', dest: 'Scripts' }
    - { path: 'GitHub', dest: 'GitHub' }
  when: setup_owncloud.0 is defined

- name: setup path symlinks /home/username/.config
  file:
    src: "/home/{{system_username}}/ownCloud/config/{{ item.path }}"
    dest: "/home/{{system_username}}/.config/{{ item.path }}"
    state: link
    force: yes
  with_items:
    - { path: 'sublime-text-3' }
    - { path: 'caffeine' }
    - { path: 'screencloud' }
    - { path: 'systemd' }
    - { path: 'mpd' }
    - { path: 'gtk-3.0' }
    - { path: 'gtk-2.0' }
    - { path: 'dunst' }
    - { path: 'termite' }
    - { path: 'polybar' }
    - { path: 'rofi' }
    - { path: 'sway' }
    - { path: 'waybar' }
  when: setup_owncloud.0 is defined

- name: Find bash scripts to make executeable
  find:
    path: "/home/{{system_username}}/ownCloud/dotfiles"
    recurse: yes
    patterns: "*.sh"
  register: find_results

- name: Find bash scripts to make executeable
  find:
    path: "/home/{{system_username}}/ownCloud/config"
    recurse: yes
    patterns: "*.sh"
  register: find_results2

- name: Update files to executeable
  file:
    path: "{{item['path']}}"
    owner: "{{system_username}}"
    group: "{{system_group}}"
    mode: 0755
  with_items:
    - "{{find_results['files'] }}"
    - "{{find_results2['files'] }}"

- name: Ensure pub keys are 0400
  file:
    path: "/home/{{system_username}}/.ssh/{{ item.path }}"
    owner: "{{system_username}}"
    group: "{{system_group}}"
    mode: 0400
  with_items:
    - { path: 'id_rsa'}
    - { path: 'id_rsa.pub'}
    - { path: 'id_rsa-aur'}
    - { path: 'id_rsa-aur.pub'}
