---
- name: install aur packages
  command: "yay --answerclean All --answerdiff All {{item}}"
  become: no
  ignore_errors: yes
  with_items:
    - ly
    - caffeine-ng
    - flacon #flac
    - google-chrome
    - gsimplecal
    - mpdscribble
    - numix-circle-icon-theme-git
    - numix-icon-theme-git
    - oh-my-zsh-git
    - pasystray
    - powerline-fonts-git #zsh theme agnoster
    - purple-facebook
    - waybar
    - reflector-timer
    - aws2-wrap
#    - roccat-tools-full
    - samsung-printers
    - grim
    - spotify
    - sublime-text-dev
    - ttf-font-awesome-4
    - get_iplayer
    - rclone-browser
    - redshift-wayland-git
    - slack-desktop
    - wlogout
    - ttf-inconsolata-g #terminator
#    - vim-youcompleteme-git
#    - gifcast
#    - dell-srvadmin
#
