---

- name: setup owncloud
  command: "owncloudcmd --user {{owncloud_username}} --password {{owncloud_password}} --non-interactive --trust $HOME/.local/share/data/ownCloud https://bcc.linaro.org/owncloud"
  register: setup_owncloud

- name: launch ownCloud
  command: "owncloud &"
  when: setup_owncloud|changed
  ignore_errors: yes
  sudo_user: "{{system_username}}"