---

- name: create user
  user:
    name: "{{system_username}}"
    password: "{{user_password|password_hash('sha512') }}"
    state: present
    groups: "docker,wheel,users,lp,storage,audio,input"
    append: yes
    shell: /bin/zsh
    update_password: always


- name: create default directories
  file:
    dest: "/home/{{system_username}}/{{item}}"
    state: directory
    owner: "{{system_username}}"
    group: "{{system_group}}"
  with_items:
    - Downloads
    - Photos
    - Music
    - ownCloud

- name: Allow group "wheel" to have sudoless root
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"

- name: Ensure zabbix is added to sudoers.d
  copy:
    src: files/etc/sudoers.d/zabbix
    dest: /etc/sudoers.d/zabbix
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
