---

- name: Ensure that ~/.gnupg directory exists
  file:
    path: '/{{root_user}}/.gnupg'
    state: 'directory'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: '0700'

- name: download pacman mirror list
  get_url:
    url: "https://www.archlinux.org/mirrorlist/?country=FR&country=DE&country=IE&country=LU&country=CH&country=GB&protocol=http&ip_version=4&ip_version=6&use_mirror_status=on"
    dest: "/etc/pacman.d/mirrorlist"

- name: "uncomment `#Server` in pacman mirror list"
  replace:
    dest: "/etc/pacman.d/mirrorlist"
    regexp: '^#Server'
    replace: 'Server'

- name: "uncomment colors"
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    regexp: "^Color"
    insertafter: "^#Color"
    line: "Color"

# Enable multilib

- name: add multilib
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "[multilib]"
    regexp: "^\\[multilib\\]"
    insertafter: "^#\\[multilib\\]"

- name: add multilib (cont)
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "Include = /etc/pacman.d/mirrorlist"
    insertafter: "^\\[multilib\\]"
    regexp: "Include = /etc/pacman.d/mirrorlist"

- name: install pacman packages
  pacman:
    name: "{{item}}"
    update_cache: yes
  when: setup_packages.0 is defined
  with_items:
# system packages
#    - base-devel #gcc
    - curl
    - htop
    - iotop
    - powertop
    - glances
    - sudo
    - zsh
    - avahi
    - tlp
    - acpi
    - acpid
    - alsa-utils
    - pulseaudio
    - pulseaudio-alsa
    - keychain
    - rsync
    - ntp
    - smartmontools
    - strace
    - dhclient
    - diffutils
    - lm_sensors
    - fuse-exfat
    - nfs-utils
    - openssh
    - sshpass
    - dnsutils
    - whois
    - wget
    - stress
    - cpupower
    - iptraf-ng
    - dosfstools
    - mosh
    - nmap
    - reflector
    - mlocate
    - binutils
    - fakeroot
    - patch
    - make
    - gcc-multilib
    - autoconf
    - automake
    - sane
    - pacman-contrib

# display packages
    - xorg-xwayland
    - grim #screenshots
      #    - xorg-xsetroot
      #    - xorg-server
      #    - xorg-server-devel
      #    - xorg-xkill
      #    - arandr
      #    - xorg-xinit
      #    - gdm

# window manager packages
    - sway
    - rofi
    - swaylock
    - numix-gtk-theme
    - arc-gtk-theme
    - arc-icon-theme
    - lxappearance
    - perl-anyevent-i3
    - perl-json-xs
    - xautolock
    - seahorse
    - networkmanager
    - network-manager-applet
    - networkmanager-openvpn
    - mako
    - thunar-volman
    - thunar

# compression packages
    - xarchiver-gtk2
    - zip
    - unzip
    - unrar
    - bzip2
    - gzip
    - tar
    - p7zip

# virtualization packages
    - docker
    - lxc
    - lxcfs
    - qemu
    - qemu-arch-extra

# file packages
    - nautilus
    - ranger
    - gphoto2
    - libgphoto2 #gphoto2
#    - gvfs gvfs-gphoto2 gvfs-mtp gvfs-smb # have to be bundled together as they depend on each other
    - rclone

# office packages
    - libreoffice-fresh
    - gthumb
#    - chromium #google-chrome aur
    - pepper-flash
    - deluge-gtk
    - variety
    - gnome-keyring
    - vim-jedi
    - gnome-calculator
    - feh
    - atom

# printing packages
    - cups

# chat packages
#   - pidgin
#    - weechat

# font packages
    - freetype2
    - fontconfig
    - cairo
    - ttf-dejavu
    - noto-fonts
    - noto-fonts-cjk
    - ttf-dejavu
    - ttf-liberation

# gaming/video/music packages
#    - steam
#    - steam-libs
    - vlc
    - ncmpcpp
    - mpd
    - mpc
    - pavucontrol
#    - gstreamer0.10-base-plugins
    - picard
    - lib32-alsa-plugins
#    - mumble
#    - cheese
#    - gstreamer0.10-good-plugins
#    - gstreamer0.10-bad-plugins
#    - gstreamer0.10-ugly-plugins

# terminal/work packages
    - gist
    - ncdu
    - xsel
    - ranger
    - dos2unix
#    - grml-zsh-config
    - kitty
    - git
    - git-review
    - screen
    - tmux
#    - thunderbird

# Python2 packages
#   - python2
#    - ipython2
#    - python2-virtualenv
#    - python2-pip
 # Python3
    - python
    - python-virtualenv
    - ipython
    - python-pip
    - pyenv
    - python-pipenv

#Steam/Mesa (Graphics)
#    - steam-native-runtime
    - mesa
#    - mesa-libgl
#    - lib32-mesa
#    - mesa-vdpau
#    - sdl2_image
#    - sdl_image
#    - lib32-sdl
#    - lib32-sdl2
