# Download an up-to-date pacman mirror list for Europe
# add multilib and infinality (fonts) repositories
# install catalyst drivers, when configure_catalyst is defined
# install base packages
---

- name: Ensure that ~/.gnupg directory exists
  file:
    path: '/{{root_user}}/.gnupg'
    state: 'directory'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: '0700'

- name: download pacman mirror list
  get_url:
    url: "https://www.archlinux.org/mirrorlist/?country=FR&country=DE&country=IE&country=LU&country=CH&country=GB&protocol=http&ip_version=4&ip_version=6&use_mirror_status=on"
    dest: "/etc/pacman.d/mirrorlist"

- name: "uncomment `#Server` in pacman mirror list"
  replace:
    dest: "/etc/pacman.d/mirrorlist"
    regexp: '^#Server'
    replace: 'Server'

- name: "uncomment colors"
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    regexp: "^Color"
    insertafter: "^#Color"
    line: "Color"

# Enable multilib

- name: add multilib
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "[multilib]"
    regexp: "^\\[multilib\\]"
    insertafter: "^#\\[multilib\\]"

- name: add multilib (cont)
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "Include = /etc/pacman.d/mirrorlist"
    insertafter: "^\\[multilib\\]"
    regexp: "Include = /etc/pacman.d/mirrorlist"

## infinality font bundle

#- name: add infinality-bundle key
#  shell: "pacman-key -r 962DDE58 && pacman-key --lsign-key 962DDE58"
#  changed_when: false

#- name: add infinality-bundle # https://wiki.archlinux.org/index.php/Unofficial_user_repositories#infinality-bundle
#  lineinfile:
#    dest: /etc/pacman.conf
#    state: "present"
#    line: "[infinality-bundle]"

#- name: add infinality-bundle (cont)
#  lineinfile:
#    dest: /etc/pacman.conf
#    state: present
#    line: "Server = http://bohoomil.com/repo/$arch"
#    insertafter: "^\\[infinality\\-bundle\\]"

#- name: add infinality-bundle-fonts # https://wiki.archlinux.org/index.php/Unofficial_user_repositories#infinality-bundle
#  lineinfile:
#    dest: /etc/pacman.conf
#    state: present
#    line: "[infinality-bundle-fonts]"

#- name: add infinality-bundle-fonts (cont)
#  lineinfile:
#    dest: /etc/pacman.conf
#    state: present
#    line: "Server = http://bohoomil.com/repo/fonts"
#    insertafter: "^\\[infinality\\-bundle\\-fonts\\]"

# https://wiki.archlinux.org/index.php/unofficial_user_repositories#alucryd-multilib
#- name: add steamlibs
# blockinfile:
#    dest: /etc/pacman.conf
#    insertbefore: "^\\[testing\\]"
#    block: |
#      [alucryd-multilib]
#      Server = http://pkgbuild.com/~alucryd/$repo/x86_64

- name: install pacman packages
  pacman:
    name: "{{item}}"
    state: latest
    update_cache: yes
  when: setup_packages.0 is defined
  with_items:
# system packages
    - abs
#    - base-devel #gcc
    - curl
    - htop
    - iotop
    - powertop
    - glances
    - sudo
    - zsh
    - udiskie
    - avahi
    - xbindkeys
    - tlp
    - acpi
    - acpid
    - alsa-utils
    - pulseaudio
    - pulseaudio-alsa
    - keychain
    - rsync
    - ntp
    - smartmontools
    - strace
    - dhcpcd
    - dhclient
    - diffutils
    - lm_sensors
    - jdk8-openjdk
    - fuse-exfat
    - nfs-utils
    - logrotate
    - openssh
    - dnsutils
    - whois
    - wget
    - stress
    - cpupower
    - iptraf-ng
    - dosfstools
    - mosh
    - nmap
    - reflector
    - mlocate
    - binutils
    - fakeroot
    - patch
    - make
    - gcc-multilib
    - autoconf
    - automake
    - netdata

# display packages
    - xorg-xbacklight
    - xorg-xsetroot
    - xorg-server
    - xorg-server-devel
    - xorg-xkill
    - arandr
    - xorg-xinit
    - lightdm
    - lightdm-gtk-greeter
    - lightdm-gtk-greeter-settings
    - redshift

# window manager packages
    - i3-wm
    - dmenu
    - rofi
#    - i3lock
    - i3status
    - xfce4-notifyd
#    - conky # (polybar aur)
    - screenfetch
    - numix-themes
    - arc-gtk-theme
    - arc-icon-theme
    - lxappearance
    - perl-anyevent-i3
    - perl-json-xs
    - xautolock
    - seahorse
    - dunst
    - networkmanager
    - network-manager-applet
    - networkmanager-openvpn
    - gsimplecal

# compression packages
    - xarchiver-gtk2
    - zip
    - unzip
    - unrar
    - bzip2
    - gzip
    - tar
    - p7zip

# virtualization packages
    - docker
    - lxc
    - lxcfs
    - qemu

# file packages
    - nautilus
    - ranger
    - gphoto2
    - libgphoto2 #gphoto2
    - gvfs gvfs-gphoto2 gvfs-mtp gvfs-smb # have to be bundled together as they depend on each other

# office packages
    - libreoffice-fresh
    - gthumb
    - owncloud-client
#    - chromium #google-chrome aur
    - transmission-qt
    - variety
    - gnome-keyring
    - vim-jedi
    - gnome-calculator
    - feh

# printing packages
    - cups

# chat packages
    - pidgin
#    - weechat

# font packages
    - freetype2
    - fontconfig
    - cairo
    - ttf-dejavu
    - noto-fonts
    - noto-fonts-cjk

# gaming/video/music packages
#    - steam
#    - steam-libs
    - vlc
    - kodi
    - ncmpcpp
    - mpd
    - mpc
    - pavucontrol
#    - gstreamer0.10-base-plugins
    - picard
    - lib32-alsa-plugins
    - mumble
    - cheese
#    - gstreamer0.10-good-plugins
#    - gstreamer0.10-bad-plugins
#    - gstreamer0.10-ugly-plugins

# terminal/work packages
    - gist
    - ncdu
    - xsel
    - ranger
    - dos2unix
#    - grml-zsh-config
    - termite
    - git
    - git-review
    - screen
    - tmux
    - thunderbird
    - hunspell-en

# Python2 packages
    - python2
    - ipython2
    - python2-virtualenv
    - python2-pip
    - python2-jedi
 # Python3
    - python
    - python-virtualenv
    - ipython
    - python-pip

#Steam/Mesa (Graphics)
    - steam-native-runtime
    - mesa
    - mesa-libgl
    - lib32-mesa-libgl
    - mesa-vdpau
    - sdl2_image
    - sdl_image
    - lib32-sdl
    - lib32-sdl2
