---

- name: install yaourt
  pacman:
    name: yaourt
    state: latest

- name: install yaourt packages (this can take some time...)
  pacman:
    name: "{{item}}"
    state: latest
    aur: yes
  ignore_errors: yes
  with_items:
    - oh-my-zsh-git
    - apachedirectorystudio
    - xfce4-volumed
    - caffeine-ng
    - conkyclementine-bzr
    - i3lock-wrapper
    - i3lock-blur
    - keepass-plugin-http
    - pycharm-community
    - python2-cli53
    - screencloud
    - skype4pidgin-git
    - solaar
    - spotify
    - teamviewer
    - whatpulse
    - zabbix-agent
    - numix-circle-icon-theme-git
    - numix-icon-theme-git
    - google-talkplugin
    - vim-youcompleteme-git
    - j4-dmenu-desktop
    - chromium-pepper-flash
    - backintime-cli
    - backintime
