---

- name: create user
  user:
    name: "{{system_username}}"
    password: "{{user_password|password_hash('sha512') }}"
    state: present
    groups: "docker,wheel,users,lp,storage,audio"
    append: yes
    shell: /bin/zsh
    update_password: always
  sudo: yes


- name: create default directories
  file:
    dest: "/home/{{system_username}}/{{item}}"
    state: directory
    owner: "{{system_username}}"
    group: "{{system_group}}"
  with_items:
    - Downloads
    - Photos
    - Music
    - ownCloud

- name: copy Templates folder
  copy:
    src: "files/home/Templates"
    dest: "/home/{{system_username}}/Templates"
    owner: "{{system_username}}"
    group: "{{system_group}}"
    mode: 0644
